# Generated by Django 4.0.2 on 2022-03-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='This is Lyrics'),
        ),
    ]
