# Generated by Django 4.0.2 on 2022-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_song_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_restriction', models.TextField(blank=True, max_length=200, null=True)),
                ('password_restriction', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
