# Generated by Django 4.0.2 on 2022-03-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password_restriction',
            field=models.TextField(default='bad'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username_restriction',
            field=models.TextField(default='good'),
        ),
    ]
